name: CI

on:
  push:
  pull_request:

jobs:
  Luau:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
      - name: Install dependencies
        run: rokit install --no-trust-check
      - name: Run Stylua
        run: stylua --check src
      - name: Run Selene
        run: selene src
  Python:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: "app"
